name: run code and publish files

on:
  push:
  schedule:
      - cron:  "0 1 * * 2"
      #https://crontab.guru/#0_1_*_*_2

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true
  
jobs:
    
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Install Dependencies 
        run: |
            python -m pip install --upgrade pip
            python -m pip install requests

      - name: Execute Code
        run: python main.py 

      - name: Create tag with timestamp
        id: tag_version
        run: |
          TAG="auto-release-$(date +'%Y%m%d')"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG
          git push origin $TAG

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.tag }}
          name: "Automated update for JMDict ${{ steps.tag_version.outputs.tag }}"
          body: "This is an weekly automated release with data from the latest repositories."
          files: |
            results/jmdictExtended.json
            results/jmdictExtended.json.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with: 
            name: jmdict_extended_report
            path: jmdict_extended_report/
            retention-days: 30
    


#executeJob:      
#publishJob:
#    needs: executeJob
