name: run code and publish files

on:
  push:
  schedule:
      - cron:  "0 1 * * 2"

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true

permissions:
  contents: write
  
jobs:
    
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Install Dependencies 
        run: |
            python -m pip install --upgrade pip
            python -m pip install requests

      - name: Execute Code
        run: python main.py 

      - name: Create tag with timestamp
        id: tag_version
        run: |
          TAG="1.1.1-auto-release-$(date +'%Y-%m-%d')"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Bluskyo/JMDict_Extended.git
          git push origin $TAG

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_TOKEN }} 
          tag_name: ${{ steps.tag_version.outputs.tag }}
          name: "${{ steps.tag_version.outputs.tag }}"
          body: "This is an weekly automated release with updated data from (mostly JMDict) the latest repositories."
          files: |
            results/jmdictExtended.json
            results/jmdictExtended.json.zip